### PR TITLE
Fix alternate ship colors not displaying in palettes other than GROUPA

### PR DESCRIPTION
**Pull request by SiriusTR**
The code used in D2 to replace colors for players 5/6 with purple and white only worked in levels using groupa.pig. This is because it was doing pixel-matching on the palettized texture bitmaps, and the palette indices used for each pixel were not consistent between palettes.
I've replaced it with a simple GameBitmaps lookup. Honestly it seems so simple in comparison that I'm worried I might be making a mistake here, but it did seem to work when I tested it in game.
I haven't made any changes to the system used in D1, since it does at least work there. Let me know if you think I should.

### CODE REVIEW

**Comment by arbruijn** [comment]
Looks fine to me, this should also work better for custom pyro textures with the same colors I suppose. For the original pig+ham files it doesn't matter, but in case someone reorganized the bitmaps it might be better to find the bitmap index by name? Should be `piggy_find_bitmap("ship6-4")` for 103

**Comment by SiriusTR** [comment]
That makes sense, then D1 and D2 can share the same code. Updated

**Comment by arbruijn** [comment]
I realized later it makes more sense to directly compare the bitmap name instead of looking up the index. Something like the following. Maybe change that one last time?
```c
const char *bm_name = piggy_game_bitmap_name(bm);
char is_white_tex1 = bm_name && !strcmp(bm_name, "ship7-4");
```

**Review by arbruijn — APPROVED** [review]

**Comment by arbruijn** [comment]
Sorry, forgot to check how bitmapname was initialized and I see now that's behind an ifdef and ogl_allow_png() condition. Setting bitmapname should probably be moved out of that if.

**Pull request merged**
