### PR TITLE
Observer mode: Allow per game type configuration

### LINKED ISSUE #55: Observer mode: Allow per game type configuration
I've observed some users (e.g. particularly roncli) changing settings between FFA and 1v1 matches. It might save time to allow separate configurations for relevant modes: 1v1, FFA, teams, co-op.
I'm not sure what a good UI presentation for this would look like. The simplest would be "your configuration applies to whatever the current game type is", but that requires you to join/host a game of that type before you can configure it, which might not be ideal.

### PR DESCRIPTION
**Pull request by SiriusTR**
This change allows observer mode preferences to be set differently for different game types. The game types don't map exactly to `Netgame` settings at present since some are loosely defined; instead the current ones are
1. 1v1: anarchy with only two players
2. FFA (free-for-all): anarchy with more than two players
3. Teams: Any multiplayer mode that uses the GM_TEAM flag
4. Co-op: Any multiplayer mode that uses the GM_MULTI_COOP flag

The modes are defined in get_observer_game_mode in multi.c. This could be extended in future if we find the current modes are not sufficient.
Backward-compatibility code is added to playsave.c to migrate old observer presets to the new format; it will copy the old settings to all modes if it finds them.

This pull request resolves #55.

### CODE REVIEW

**Comment by arbruijn** [comment]
I have finally tested the changes, sorry it took so long. Thank you for the share settings toggle, quite nicely integrated with the ui.

A few more remarks.

With a non-observer player I get an assertion failure on `Assert(is_observer());` in get_observer_game_mode because the 'list of observers' option is also used for non-observers. 

Maybe it would be nice to start the option screen with the current mode while observing? Something like the following at the top of do_obs_menu:
`if (is_observer())`
`    obs_menu_data.mode = get_observer_game_mode();`

And I noticed the title of the menu is 'jinx mode options', this might have been an earlier name for observer mode? Maybe now is a good time to change it.

**Comment by SiriusTR** [comment]
Alright, I'll take a look at that - should be possible to fix.

> And I noticed the title of the menu is 'jinx mode options', this might have been an earlier name for observer mode? Maybe now is a good time to change it.

I think I would want to check with the community on this one - I believe this was kind of a tribute to the guy who did the initial work on observer mode. @roncli might know.

**Comment by roncli** [comment]
Drakona probably added that.  You can replace it with something more contextual.

**Comment by arbruijn** [comment]
Ah I now see a comment from Lothar on the DCL discord about it, we should probably leave it as is.

**Pull request merged**
